In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_colwidth", 200)
pd.set_option("display.max_columns", None)

In [2]:
import os
print("CWD:", os.getcwd())

CWD: C:\Users\emmab\Downloads\honsProject\notebooks

In [3]:
# Load LIAR dataset splits
liar_train = pd.read_csv("../data/liar/train.tsv", sep="\t", header=None)
liar_valid = pd.read_csv("../data/liar/valid.tsv", sep="\t", header=None)
liar_test  = pd.read_csv("../data/liar/test.tsv",  sep="\t", header=None)

print("LIAR shapes:")
print("Train:", liar_train.shape)
print("Valid:", liar_valid.shape)
print("Test :", liar_test.shape)

LIAR shapes:
Train: (10240, 14)
Valid: (1284, 14)
Test : (1267, 14)

In [4]:
liar_columns = [
    "id", "label", "statement", "subject", "speaker",
    "job", "state", "party",
    "barely_true", "false", "half_true",
    "mostly_true", "pants_on_fire", "context"
]

liar_train.columns = liar_columns
liar_valid.columns = liar_columns
liar_test.columns  = liar_columns

In [5]:
liar_train = liar_train[["statement", "label"]]
liar_valid = liar_valid[["statement", "label"]]
liar_test  = liar_test[["statement", "label"]]

liar_train.head()

,statement,label
0,Says the Annies List political group supports third-trimester abortions on demand.,false
1,When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration.,half-true
2,"Hillary Clinton agrees with John McCain ""by voting to give George Bush the benefit of the doubt on Iran.""",mostly-true
3,Health care reform legislation is likely to mandate free sex change surgeries.,false
4,The economic turnaround started at the end of my term.,half-true

In [6]:
fake_labels = {"false", "barely-true", "pants-on-fire"}

def convert_liar_label(label):
    label = str(label).strip().lower()
    return 0 if label in fake_labels else 1

liar_train["label"] = liar_train["label"].apply(convert_liar_label)
liar_valid["label"] = liar_valid["label"].apply(convert_liar_label)
liar_test["label"]  = liar_test["label"].apply(convert_liar_label)

In [7]:
print("LIAR train label counts:\n", liar_train["label"].value_counts(dropna=False))
print("LIAR valid label counts:\n", liar_valid["label"].value_counts(dropna=False))
print("LIAR test  label counts:\n", liar_test["label"].value_counts(dropna=False))

LIAR train label counts:
 label
1    6591
0    3649
Name: count, dtype: int64
LIAR valid label counts:
 label
1    784
0    500
Name: count, dtype: int64
LIAR test  label counts:
 label
1    806
0    461
Name: count, dtype: int64

In [8]:
print("LIAR Train label distribution:")
print(liar_train["label"].value_counts())

print("\nLIAR Test label distribution:")
print(liar_test["label"].value_counts())

LIAR Train label distribution:
label
1    6591
0    3649
Name: count, dtype: int64

LIAR Test label distribution:
label
1    806
0    461
Name: count, dtype: int64

In [9]:
# Load ISOT dataset files
fake_news = pd.read_csv("../data/isot/Fake.csv")
real_news = pd.read_csv("../data/isot/True.csv")

print("ISOT raw shapes:")
print("Fake:", fake_news.shape)
print("Real:", real_news.shape)

ISOT raw shapes:
Fake: (23481, 4)
Real: (21417, 4)

In [10]:
fake_news["label"] = 0
real_news["label"] = 1

isot = pd.concat([fake_news, real_news], axis=0)

# Keep only text + label
isot = isot[["text", "label"]]
isot.columns = ["statement", "label"]

isot.head()

,statement,label
0,"Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and the very dishonest fake news media. The former...",0
1,"House Intelligence Committee Chairman Devin Nunes is going to have a bad day. He s been under the assumption, like many of us, that the Christopher Steele-dossier was what prompted the Russia inve...",0
2,"On Friday, it was revealed that former Milwaukee Sheriff David Clarke, who was being considered for Homeland Security Secretary in Donald Trump s administration, has an email scandal of his own.In...",0
3,"On Christmas day, Donald Trump announced that he would be back to work the following day, but he is golfing for the fourth day in a row. The former reality show star blasted former President Bar...",0
4,Pope Francis used his annual Christmas Day message to rebuke Donald Trump without even mentioning his name. The Pope delivered his message just days after members of the United Nations condemned T...,0

In [11]:
isot = isot.sample(frac=1, random_state=42).reset_index(drop=True)

In [12]:
print("ISOT label distribution:")
print(isot["label"].value_counts())

ISOT label distribution:
label
0    23481
1    21417
Name: count, dtype: int64

In [13]:
print("Missing values check:")

print("\nLIAR Train:")
print(liar_train.isnull().sum())

print("\nISOT:")
print(isot.isnull().sum())

Missing values check:

LIAR Train:
statement    0
label        0
dtype: int64

ISOT:
statement    0
label        0
dtype: int64

In [14]:
print("Final dataset summaries:")
print("\nLIAR Train:", liar_train.shape)
print("LIAR Valid:", liar_valid.shape)
print("LIAR Test :", liar_test.shape)
print("ISOT Total:", isot.shape)

Final dataset summaries:

LIAR Train: (10240, 2)
LIAR Valid: (1284, 2)
LIAR Test : (1267, 2)
ISOT Total: (44898, 2)

In [15]:
liar_train.to_csv("../data/liar/liar_train_clean.csv", index=False)
liar_valid.to_csv("../data/liar/liar_valid_clean.csv", index=False)
liar_test.to_csv("../data/liar/liar_test_clean.csv", index=False)

isot.to_csv("../data/isot/isot_clean.csv", index=False)

print("Cleaned datasets saved.")

Cleaned datasets saved.

In [16]:
print(liar_train["label"].unique())

[0 1]